
package com.javaws.services;

import java.util.List;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EtudiantWS", targetNamespace = "http://services.javaws.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EtudiantWS {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSize", targetNamespace = "http://services.javaws.com/", className = "com.javaws.services.GetSize")
    @ResponseWrapper(localName = "getSizeResponse", targetNamespace = "http://services.javaws.com/", className = "com.javaws.services.GetSizeResponse")
    @Action(input = "http://services.javaws.com/EtudiantWS/getSizeRequest", output = "http://services.javaws.com/EtudiantWS/getSizeResponse")
    public int getSize();

    /**
     * 
     * @param nom
     * @param prenom
     * @param moyenne
     */
    @WebMethod
    @RequestWrapper(localName = "newStudent", targetNamespace = "http://services.javaws.com/", className = "com.javaws.services.NewStudent")
    @ResponseWrapper(localName = "newStudentResponse", targetNamespace = "http://services.javaws.com/", className = "com.javaws.services.NewStudentResponse")
    @Action(input = "http://services.javaws.com/EtudiantWS/newStudentRequest", output = "http://services.javaws.com/EtudiantWS/newStudentResponse")
    public void newStudent(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "moyenne", targetNamespace = "")
        double moyenne);

    /**
     * 
     * @return
     *     returns java.util.List<com.javaws.services.Etudiant>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEtudiants", targetNamespace = "http://services.javaws.com/", className = "com.javaws.services.GetEtudiants")
    @ResponseWrapper(localName = "getEtudiantsResponse", targetNamespace = "http://services.javaws.com/", className = "com.javaws.services.GetEtudiantsResponse")
    @Action(input = "http://services.javaws.com/EtudiantWS/getEtudiantsRequest", output = "http://services.javaws.com/EtudiantWS/getEtudiantsResponse")
    public List<Etudiant> getEtudiants();

    /**
     * 
     * @param nom
     * @param prenom
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMoyenne", targetNamespace = "http://services.javaws.com/", className = "com.javaws.services.GetMoyenne")
    @ResponseWrapper(localName = "getMoyenneResponse", targetNamespace = "http://services.javaws.com/", className = "com.javaws.services.GetMoyenneResponse")
    @Action(input = "http://services.javaws.com/EtudiantWS/getMoyenneRequest", output = "http://services.javaws.com/EtudiantWS/getMoyenneResponse")
    public double getMoyenne(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom);

}
